config/routes.rb
Rails.application.routes.draw do

  resources :affiliate_dashboards
  devise_for :affiliates
  resources :affiliates
  resources :video_orders


  authenticated :affiliate do
    get 'a/clients' => 'affiliate_dashboards#clients'

  end

get 'client/:id', to: "affiliate_dashboard#client_page"

  authenticated :user, ->(user) { user.buyer? } do
    get 'c/shouts' => 'customer_dashboard#purchases'
    get 'c/dashboard' => 'customer_dashboard#buyer_dashboard'
  end


  resources :admin_dashboard
  # resources :stripe_accounts
  # resources :user_listings
  mount StripeEvent::Engine, at: '/stripe-events' # provide a custom path


  authenticated :user, ->(user) { user.admin? } do
    mount Blazer::Engine, at: "blazer"

    get 'admin/admins' => 'admin_dashboard#admins'
    get 'admin/users' => 'admin_dashboard#users'
    get 'admin/sellers' => 'admin_dashboard#sellers'
    get 'admin/buyers' => 'admin_dashboard#buyers'
    get 'admin/affiliates' => 'admin_dashboard#affiliates'
    get 'admin/orders' => 'admin_dashboard#orders'
    get 'admin/listings' => 'admin_dashboard#listings'
    get 'admin/analytics' => 'admin_dashboard#website_analytics'


    get 'admin/create_seller' => 'users#new'
    post 'admin/create_seller' => 'users#add_user'

  end

  devise_for :buyers
  resources :orders
  devise_for :users, controllers: { confirmations: 'confirmations' }

  resources :users

  resources :stripe_accounts

  resources :bank_accounts

  resources :orders do
    resources :video_orders
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :listings do
    resources :orders
  end

    resources :orders

resources :bank_accounts


  get 'stripe_show' => "stripe_accounts#show"


  get 'stripe_' => "stripe_account#create"

  get 'stripe_new' => "stripe_account#new"

  get 'cancel' => "orders#cancel_update"


  get 'seller' => "listings#seller"

  get 'edit_stripe' => "stripe_accounts#edit"




  #new_order_sales_upload post '/orders/:order_ids(.:format) sales_uploads#new'
 get 'sales' => "orders#sales"
 post 'sales' => "orders#sales"

  get 'talent' => "listings#listings_page"

  get 'purchases' => "orders#purchases"

  get 'buyer_purchases' => "orders#buyer_purchases"



  get 'dashboard' => "dashboard#dashboard"
  get 'shouts' => "dashboard#tables"
  get 'charts' => "dashboard#charts"
  get 'settings' => "dashboard#settings"
  get 'account' => "dashboard#account"
  get 'payout_destination' => "dashboard#payout_destination"

  get 'account_affiliate' => "affiliate_dashboards#account_affiliate"


get 'auth' => "users#index"

get 'stripe' => "listings#stripe"

get 'analytics' => "dashboard#order_analytics"





  get 'car' => "listings#carousel"

  root to: "listings#index"



end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate
  # load_and_authorize_resource
  layout :determine_layout


  def account

    @balance = Stripe::Balance.retrieve(
      { stripe_account: (current_user || current_affiliate).stripe_account.acct_id }
    )


    @transaction = Stripe::BalanceTransaction.all(
      {
        :limit => 10,
        type: 'payment',
        available_on: { gt: Time.now.to_i },
      },
        { stripe_account: (current_user || current_affiliate).stripe_account.acct_id }
    )

    @transaction_1 = Stripe::BalanceTransaction.all(
      {
        :limit => 1,
        type: 'payment',
        available_on: { gt: Time.now.to_i },
      },
        { stripe_account: (current_user || current_affiliate).stripe_account.acct_id }
    )

    @transfer = Stripe::Transfer.list(
      {
        limit: 100
      },
      {stripe_account: (current_user || current_affiliate).stripe_account.acct_id }
    )

    @payments = Stripe::Charge.list(
      {
        limit: 100, # The number of charges to retrieve (between 1 and 100)
        expand: ['data.source_transfer', 'data.application_fee'] # Expand other objects for additional detail
      },
      { stripe_account: (current_user || current_affiliate).stripe_account.acct_id } # The Stripe ID of the user viewing the dashboard
    )

    @payouts = Stripe::Payout.list(
      {
        limit: 100,
        expand: ['data.destination'] # Get some extra detail about the bank account
      },
      { stripe_account: (current_user || current_affiliate).stripe_account.acct_id } # Again, authenticating with the ID of the connected account
    )

    @payout_1 = Stripe::Payout.list(
      {
        limit: 1,
        expand: ['data.destination'] # Get some extra detail about the bank account
      },
      { stripe_account: (current_user || current_affiliate).stripe_account.acct_id } # Again, authenticating with the ID of the connected account
    )



  end

  def payout_destination

    @txns = Stripe::BalanceTransaction.list(
      {
        payout: params[:id], # The ID of the payout you want transactions for
        expand: ['data.source.source_transfer'], # Expand the source_transfer for extra detail
        limit: 100
      },
      { stripe_account: (current_user || current_affiliate).stripe_account.acct_id }
    )

  end


  def settings
    @user = (current_user || current_affiliate)
    @stripe_account = (current_user || current_affiliate).stripe_account
  end

  def order_analytics
    @orders_referring = Order.where(seller: current_user).joins(:visit).group("referring_domain").count
    @orders_country = Order.where(seller: current_user).joins(:visit).group("city").count
    # @listing_visits = Ahoy::Event.where(name: "Listing Viewed").where_properties(listing_id: current_user).count

  end

  def dashboard

    @orders_a = Order.all.where(seller: current_user).paginate(:page => params[:month_orders_page], :per_page => 12)
    @orders_b = Order.all.where(seller: current_user).paginate(:page => params[:day_orders_page], :per_page => 7)

    @orders_c = Order.all.where(seller: current_user).where("created_at < updated_at").paginate(:page => params[:month_orders_page_1], :per_page => 12)
    @orders_d = Order.all.where(seller: current_user).where("created_at < updated_at").paginate(:page => params[:day_orders_page_1], :per_page => 7)

    @orders_e = Order.all.where(seller: current_user).where(order_status: [2] ).paginate(:page => params[:month_orders_page_1], :per_page => 12)
    @orders_f = Order.all.where(seller: current_user).where(order_status: [2] ).paginate(:page => params[:day_orders_page_1], :per_page => 7)

    @orders_g = Order.all.where(seller: current_user).where(order_status: [2] )
    @orders_h = Order.all.where(seller: current_user).where(order_status: [2] )


    @orders_month = @orders_g.all.group_by { |mon|  mon.created_at.beginning_of_month }
    @orders_day = @orders_h.all.group_by { |day|  day.created_at.beginning_of_day }


    @order = Order.new

  end

  def tables

    user = current_user
    orders = Order.where(seller: user)
    orders_with_video = Order.find_by(video: present?)
    orders_charged = orders.where(order_status: [2] )
    orders_created = orders.where(order_status: [1] )


    @orders_tables = orders.order('created_at DESC').paginate(:page => params[:all_orders_page], :per_page => 15)
    @orders_tables_comp = orders_charged.order('created_at DESC').paginate(:page => params[:comp_orders_page], :per_page => 8)
    @orders_tables_up = orders_created.order('created_at DESC').paginate(:page => params[:up_orders_page], :per_page => 8)

  end

  def charts
    @orders = Order.all.where(seller: current_user).paginate(:page => params[:page], :per_page => 15) || @orders = Order.all.where(seller: current_buyer).paginate(:page => params[:page], :per_page => 15)
    @orders_month = @orders.group_by { |mon| mon.created_at.beginning_of_month }



  end


  private

  def authenticate
    if current_affiliate != nil
     authenticate_affiliate!
    else
     authenticate_user!
    end

  end

  def determine_layout
    current_affiliate ? "affiliate_dashboard" : "admin"
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper

  def as_table_row(value)
    return "#{value}"
  end

  def as_table_row_transfer(value)
    return "#{value}"
  end

  def as_table_row_transaction(value)
    return "#{value}"
  end

  def as_table_row_payout(value)
    return "#{value}"
  end

  def as_table_row_payment(value)
    return "#{value}"
  end

end

app/views/dashboard/account.html.erb
                  <div class="card-deck">
                    <div class="col-lg-4">
                        <div class="card border-success ">
                            <div class="card-header ">
                              <% @transaction_1.data.each do |transaction| %>
                                <h4 class="card-title">Next Scheduled Payout</h4>
                                <p class="card-category">Estimated Date: <%= as_table_row_transaction(Time.at(transaction["available_on"]).strftime('%B, %d, %Y on %A')) %></p>
                            </div>
                            <div class="card-body text-success">
                                  <h1>
                                      <td class="center"><%= number_to_currency(as_table_row_transaction(transaction["amount"] / 100.00 )) %></td>
                                      <td class="center"><%= as_table_row_transaction(transaction["currency"]).upcase %></td>
                                  </h1>
                              <% end %>
                            </div>
                        </div>
                      </div>
                      <div class="col-lg-4">
                          <div class="card border-primary ">
                              <div class="card-header ">
                                  <h4 class="card-title">Account Balance</h4>
                                  <p class="card-category">Your pending account settlement total</p>
                              </div>
                              <div class="card-body text-primary ">
                                <% @balance.pending.each do |balance| %>
                                    <h1><%= number_to_currency(balance["amount"] / 100.0 )  %></h1>
                                <% end %>
                              </div>
                          </div>
                      </div>
                      <div class="col-lg-4">
                          <div class="card ">
                              <div class="card-header ">
                                <% @payout_1.each do |payout| %>
                                  <h4 class="card-title">Most Recent Payout</h4>
                                  <p class="card-category">Deposited on <%= as_table_row_payout(Time.at(payout["arrival_date"]).strftime('%B, %d, %Y')) %></p>
                              </div>
                              <div class="card-body ">
                                            <h1>
                                                <td class="center"><%= number_to_currency(as_table_row_payout(payout["amount"] / 100.00 )) %></td>
                                                <td class="center"><%= as_table_row_payout(payout["currency"]).upcase %></td>
                                            </h1>
                                        <% end %>
                              </div>
                          </div>
                      </div>
                      <div class="col-lg-6 mt-5">
                          <div class="card ">
                              <div class="card-header ">
                                  <h4 class="card-title">Scheduled Payouts</h4>
                                  <p class="card-category">Your scheduled payouts</p>
                              </div>
                              <div class="card-body ">
                                <table class="table table-bordered table-striped table-hover">
                                    <thead>
                                        <tr>
                                            <!-- <th>Currency</th> -->
                                            <th class="center">Amount</th>
                                            <th class="center">Available On (est.)</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <% @transaction.data.each do |transaction| %>
                                            <tr>
                                                <!-- <td><%= as_table_row_transaction(transaction["currency"]).upcase %></td> -->
                                                <td class="center"><%= number_to_currency(as_table_row_transaction(transaction["amount"] / 100.00 )) %></td>
                                                <!-- <td><%= as_table_row_transaction(transaction["type"]) %></td> -->
                                                <td class="center"><%= as_table_row_transaction(Time.at(transaction["available_on"]).strftime('%m/%d/%Y')) %></td>
                                            </tr>
                                        <% end %>
                                        <!-- <%= @transaction %> -->
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 mt-5">
                        <div class="card ">
                            <div class="card-header ">
                                <h4 class="card-title">Recent Payouts</h4>
                                <p class="card-category"></p>
                            </div>
                            <div class="card-body ">
                              <table class="table table-bordered table-striped table-hover">
                                  <thead>
                                      <tr>
                                          <!-- <th>Currency</th> -->
                                          <th class="center">Amount</th>
                                          <th class="center">Deposited</th>
                                      </tr>
                                  </thead>
                                  <tbody>
                                      <% @payouts.each do |payout| %>
                                          <tr>
                                              <!-- <td><%= link_to "View Details" , payout_destination_path(payout.destination) %></td> -->
                                              <!-- <td><%= as_table_row_payout(payout["currency"]) %></td> -->
                                              <td class="center"><%= number_to_currency(as_table_row_payout(payout["amount"] / 100.00 )) %></td>
                                              <td class="center"><%= as_table_row_payout(Time.at(payout["arrival_date"]).strftime('%m/%d/%Y')) %></td>

                                          </tr>
                                      <% end %>
                                  </tbody>
                              </table>
                            </div>
                            <div class="card-footer ">
                                <hr>
                                <div class="stats">
                                    <p><i class="fa fa-check"></i>View Payout Schedule</p>
                                </div>
                            </div>
                        </div>
                    </div>


            </div>
        </div>
    </div>
</body>

<script>

</script>

</html>

app/views/dashboard/order_analytics.html.erb
  <div class="card-deck">
      <div class="col-xl-6">
        <div class="center">
          <h3>Referring Site Analytics</h3>
        </div>
          <div class="card border-info">
              <table class="table table-bordered">
                  <thead>
                      <tr>
                          <th class="center">Referring Site</th>
                          <th class="center">Count</th>
                      </tr>
                  </thead>
                  <% @orders_referring.each do |referring_domain, count| %>
                  <tbody>
                      <tr>
                        <td class="center table-bordered"><%= referring_domain %></td>
                        <td class="center"><%= count %></td>
                      </tr>
                <% end %>
                  </tbody>
              </table>
          </div>
      </div>

      <div class="col-xl-6">
          <div class="card ">
              <div class="card-header ">
                  <h4 class="card-title">Location Analytics</h4>
                  <p class="card-category"></p>
              </div>
              <div class="card-body">
                  <table class="table">
                      <thead>
                          <tr>
                              <th class="center">Country</th>
                              <th class="center">Count</th>
                          </tr>
                      </thead>
                      <% @orders_country.each do |country, count| %>
                      <tbody>
                          <tr>
                            <td class="center"><%= country %></td>
                            <td class="center"><%= count %></td>
                          </tr>
                    <% end %>
                      </tbody>
                  </table>
              </div>
          </div>
      </div>
 </div>

app/views/dashboard/payout_destination.html.erb
                  <div class="row">
                      <div class="col-lg-8">
                          <div class="card ">
                              <div class="card-header ">
                                 <h4 class="card-title">Monthly Payouts</h4>
                                 <p class="card-category">Track your performance here.</p>
                              </div>
                              <div class="card-body ">
                                    <table class="table table-bordered table-striped table-hover">
                                      <thead>
                                          <tr>
                                              <th>Currency</th>
                                              <th>Amount</th>
                                              <th>Deposited</th>
                                          </tr>
                                      </thead>
                                      <tbody>
                                          <% @txns.find do |payout| %>
                                              <tr>
                                                  <td><%= as_table_row_payout(payout["currency"]) %></td>
                                                  <td><%= as_table_row_payout(payout["amount"]) %></td>
                                                  <td><%= as_table_row_payout(Time.at(payout["available_on"]).strftime('%Y-%m-%d')) %></td>

                                              </tr>
                                          <% end %>
                                      </tbody>
                                  </table>
                              </div>
                          </div>
                      </div>

            </div>
        </div>
    </div>
</body>

<script>

</script>

</html>

app/views/dashboard/settings.html.erb
<div class="card-deck">
                    <div class="col-lg-12">

                        <div class="card ">
                            <div class="card-header ">
                                <h4 class="card-title">Settings</h4>
                                <p class="card-category"> </p>
                            </div>
                            <div class="card-body">
                              <div class="row">

                              <div class="col-lg-4">
                                <div class="settings">
                                  <% if current_user %>
                                    <a href="/users/edit" class="no-decoration">
                                    <% end %>
                                    <% if current_affiliate %>
                                    <a href="/affiliates/edit" class="no-decoration">
                                    <% end %>
                                        <div class="setting-awesome-font">
                                          <i class="fa fa-user" aria-hidden="true"></i>
                                        </div>
                                        <div class="setting-text">
                                          <h5>Account</h5>
                                          <p>Manage your account login details<p>
                                        </div>
                                      </a>
                                    </a>
                                  </div>
                                </div>

                                <div class="col-lg-4">
                                  <div class="settings">
                                    <% if (current_user || current_affiliate).stripe_account %>
                                    <%= link_to stripe_account_path(@stripe_account), class: "no-decoration" do %>
                                    <div class="setting-awesome-font">
                                      <i class="fa fa-credit-card" aria-hidden="true"></i>
                                    </div>
                                    <div class="setting-text">
                                      <h5>Payout Settings</h5>
                                      <p>Enable and manage your payout settings and details<p>
                                    </div>
                                    <% end %>

                                    <% elsif (current_user || current_affiliate).stripe_account.present? ==false %>
                                    <%= link_to new_stripe_account_path, class: "no-decoration" do %>
                                    <div class="col-lg-4 settings">
                                      <div class="setting-awesome-font">
                                        <i class="fa fa-credit-card" aria-hidden="true"></i>
                                      </div>
                                      <div class="setting-text">
                                        <h5>Payout Settings</h5>
                                        <p>Enable and manage your payout settings and details<p>
                                      </div>
                                    </div>
                                    <% end %>
                                    <% end %>
                                  </div>
                                </div>

                                <% if (current_user || current_affiliate).stripe_account %>
                                <div class="col-lg-4">
                                  <div class="settings">
                                    <%= link_to account_path, class: "no-decoration" do %>
                                    <div class="setting-awesome-font">
                                      <i class="fa fa-credit-card" aria-hidden="true"></i>
                                    </div>
                                    <div class="setting-text">
                                      <h5>Payout History</h5>
                                      <p>View your payout history and scheduled settlements<p>
                                    </div>
                                    <% end %>
                                  </div>
                                </div>
                                <% end %>

                            </div>
                          </div>

                        </div>
                    </div>
                  </div>
                  </div>
                  </div>




</body>

<script>

</script>

</html>

app/views/dashboard/upload.html.erb
                    <div class="row">

                      <div class="col-md-6">
                          <div class="card strpied-tabled-with-hover">
                              <div class="card-header ">
                                  <h4 class="card-title">Your Shouts</h4>
                                  <p class="card-category">You can view and take action on your Shouts here.</p>
                              </div>
                              <div class="card-body table-full-width table-responsive">
                                <div class="padding_5">

                                <p id="notice"><%= notice %></p>

                                <p>
                                  <strong>Name:</strong>
                                  <%= @order.name %>
                                </p>

                                <p>
                                  <strong>Description:</strong>
                                  <%= @order.description %>
                                </p>


                                <%= link_to 'Edit', edit_listing_order_path(@order) %> |
                                <%= link_to 'Back', orders_path %>
                                </div>


                              </div>
                          </div>
                      </div>


                        <div class="col-md-6">
                            <div class="card strpied-tabled-with-hover">
                                <div class="card-header ">
                                    <h4 class="card-title">Your Shouts</h4>
                                    <p class="card-category">You can view and take action on your Shouts here.</p>
                                </div>
                                <div class="card-body table-full-width table-responsive">
                                  <%= form_for([@listing, @order]) do |form| %>


                                    <% if order.errors.any? %>
                                      <div id="error_explanation">
                                        <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

                                        <ul>
                                        <% order.errors.full_messages.each do |message| %>
                                          <li><%= message %></li>
                                        <% end %>
                                        </ul>
                                      </div>
                                    <% end %>

                                  <% if user_signed_in? %>
                                  <div class="field">

                                    <%= form.file_field :video %>
                                  </div>


                                  <!-- ADD EDITING -->

                                  <div class="actions">
                                    <%= form.submit "Upload", class: "btn btn-success"  %>
                                  </div>
                                  <% end %>
                                  <% end %>

                                </div>
                            </div>
                        </div>



                        <div class="col-md-12">

            <footer class="footer">
                <div class="container">
                    <nav>
                        <ul class="footer-menu">
                            <li>
                                <a href="#">
                                    Home
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Company
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Portfolio
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Blog
                                </a>
                            </li>
                        </ul>
                        <p class="copyright text-center">
                            ©
                            <script>
                                document.write(new Date().getFullYear())
                            </script>
                            <a href="http://www.creative-tim.com">Creative Tim</a>, made with love for a better web
                        </p>
                    </nav>
                </div>
            </footer>
        </div>
    </div>
  
</body>

</html>