config/routes.rb
Rails.application.routes.draw do

  resources :affiliate_dashboards
  devise_for :affiliates
  resources :affiliates
  resources :video_orders


  authenticated :affiliate do
    get 'a/clients' => 'affiliate_dashboards#clients'

  end

get 'client/:id', to: "affiliate_dashboard#client_page"

  authenticated :user, ->(user) { user.buyer? } do
    get 'c/shouts' => 'customer_dashboard#purchases'
    get 'c/dashboard' => 'customer_dashboard#buyer_dashboard'
  end


  resources :admin_dashboard
  # resources :stripe_accounts
  # resources :user_listings
  mount StripeEvent::Engine, at: '/stripe-events' # provide a custom path


  authenticated :user, ->(user) { user.admin? } do
    mount Blazer::Engine, at: "blazer"

    get 'admin/admins' => 'admin_dashboard#admins'
    get 'admin/users' => 'admin_dashboard#users'
    get 'admin/sellers' => 'admin_dashboard#sellers'
    get 'admin/buyers' => 'admin_dashboard#buyers'
    get 'admin/affiliates' => 'admin_dashboard#affiliates'
    get 'admin/orders' => 'admin_dashboard#orders'
    get 'admin/listings' => 'admin_dashboard#listings'
    get 'admin/analytics' => 'admin_dashboard#website_analytics'


    get 'admin/create_seller' => 'users#new'
    post 'admin/create_seller' => 'users#add_user'

  end

  devise_for :buyers
  resources :orders
  devise_for :users, controllers: { confirmations: 'confirmations' }

  resources :users

  resources :stripe_accounts

  resources :bank_accounts

  resources :orders do
    resources :video_orders
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :listings do
    resources :orders
  end

    resources :orders

resources :bank_accounts


  get 'stripe_show' => "stripe_accounts#show"


  get 'stripe_' => "stripe_account#create"

  get 'stripe_new' => "stripe_account#new"

  get 'cancel' => "orders#cancel_update"


  get 'seller' => "listings#seller"

  get 'edit_stripe' => "stripe_accounts#edit"




  #new_order_sales_upload post '/orders/:order_ids(.:format) sales_uploads#new'
 get 'sales' => "orders#sales"
 post 'sales' => "orders#sales"

  get 'talent' => "listings#listings_page"

  get 'purchases' => "orders#purchases"

  get 'buyer_purchases' => "orders#buyer_purchases"



  get 'dashboard' => "dashboard#dashboard"
  get 'shouts' => "dashboard#tables"
  get 'charts' => "dashboard#charts"
  get 'settings' => "dashboard#settings"
  get 'account' => "dashboard#account"
  get 'payout_destination' => "dashboard#payout_destination"

  get 'account_affiliate' => "affiliate_dashboards#account_affiliate"


get 'auth' => "users#index"

get 'stripe' => "listings#stripe"

get 'analytics' => "dashboard#order_analytics"





  get 'car' => "listings#carousel"

  root to: "listings#index"



end

app/controllers/customer_dashboard_controller.rb
class CustomerDashboardController < ApplicationController

  before_action :check_customer
  layout "customer_dashboard"



  def purchases
    @user = current_user
    orders = Order.where(buyer: current_user)
    orders_charged = orders.where(order_status: [2] )
    orders_created = orders.where(order_status: [1] )
    @orders_pending = orders_created.order('created_at DESC').paginate(:page => params[:orders_pending_page_1], :per_page => 8)
    @orders_charged = orders_charged.order('created_at DESC').paginate(:page => params[:orders_charged_page_1], :per_page => 8)
  end

  def buyer_dashboard

    @orders_g = Order.all.where(buyer: current_user).order('created_at DESC')
    @orders_e = Order.all.where(buyer: current_user).where(order_status: [2] ).paginate(:page => params[:month_orders_page_1], :per_page => 12)
    @orders_f = Order.all.where(buyer: current_user).where(order_status: [2] ).paginate(:page => params[:day_orders_page_1], :per_page => 7)

    @orders_month = @orders_e.all.group_by { |mon|  mon.created_at.beginning_of_month }
    @orders_day = @orders_f.all.group_by { |day|  day.created_at.beginning_of_day }

  end

end

  private

  def check_customer
    unless current_user.buyer?
      if current_user.seller?
        redirect_to '/', alert: "You must be signed-in to a customer account"
      else
        redirect_to '/', alert: "You must be signed-in"
     end
   end





end

app/helpers/customer_dashboard_helper.rb
module CustomerDashboardHelper
end

app/views/customer_dashboard/buyer_dashboard.html.erb
                  <div class="card-deck">
                    <div class="col-lg-4">
                        <div class="card border-success ">
                            <div class="card-header ">
                              Total Shouts
                            </div>
                            <div class="card-body text-success">
                              <%= @orders_e.count %>
                            </div>
                        </div>
                      </div>
                      <div class="col-lg-4">
                          <div class="card border-primary ">
                              <div class="card-header ">
                                  Account Level
                              </div>
                              <div class="card-body text-primary ">
                                  Follower (Create your first shout to level up!)
                              </div>
                          </div>
                      </div>
                      <div class="col-lg-4">
                          <div class="card ">
                              <div class="card-header ">
                                  Your most recent Shout Request
                              </div>
                              <div class="card-body ">
                                <% if @orders_g.present? %>
                                  <%= @orders_g.first.name %>
                                  <br>
                                  <%= @orders_g.first.order_status %>
                                <% else %>
                                Request your first Shouts!
                                <% end %>
                              </div>
                          </div>
                      </div>
                      <div class="col-lg-6 mt-5">
                          <div class="card ">
                              <div class="card-header ">
                                  <h4 class="card-title">Your Shouts requests per month!</h4>
                                  <p class="card-category"></p>
                              </div>
                              <div class="card-body ">
                                <%= line_chart @orders_e.group_by_month(:created_at).count %>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 mt-5">
                        <div class="card ">
                            <div class="card-header ">
                                <h4 class="card-title">Payouts</h4>
                                <p class="card-category">Your past payouts</p>
                            </div>
                            <div class="card-body ">

                            </div>
                            <div class="card-footer ">
                                <hr>
                                <div class="stats">
                                    <p><i class="fa fa-check"></i>View Payout Schedule</p>
                                </div>
                            </div>
                        </div>
                    </div>


            </div>
        </div>
    </div>

app/views/customer_dashboard/purchases.html.erb
   <div class="card-deck">
      <div class="col-xl-6">
          <div class="card ">
              <div class="card-header ">
                  <h4 class="card-title">Your Shouts Requests</h4>
                  <p class="card-category">A list of all of your current requests</p>
              </div>
              <table class="table">
                <thead>
                  <tr>
                    <th class="center">Order Number</th>
                    <th class="center">Talent Name</th>
                    <th class="center">Price</th>

                    <th class="center column-remove-1">Date Requested</th>
                    <th class="center">Update</th>
                  </tr>
                </thead>
                <% @orders_pending.each do |order| %>
                  <tbody>
                    <tr>
                      <td class="center"><%= order.id %></td>
                      <td class="center"><%= order.seller.name %></td>
                      <td class="center"><%= number_to_currency(order.order_price) %></td>
                      <td class="center column-remove-1"><%= order.created_at.strftime("%B %-d, %Y") %></td>

                      <td class="center">
                            <%= link_to edit_order_path(order), class: "btn btn-link" do %>
                            <i class="fa fa-indent" aria-hidden="true"></i>
                            <% end %>
                      </td>
                    </tr>
                    <% end %>
                  </tbody>
                </table>
                <div class="digg_pagination">
                  <%= will_paginate @orders_pending, :param_name => 'orders_pending_page_1', :page_links => false %>
                </div>
           </div>
      </div>

    <div class="col-xl-6">
        <div class="card ">
            <div class="card-header ">
                <h4 class="card-title">Your Completed Shouts</h4>
                <p class="card-category">A list of all of your completed shouts ready for download!</p>
            </div>
            <div class="card-body">
                <table class="table">
                  <thead>
                    <tr>
                      <th class="center">Order Number</th>
                      <th class="center">Talent Name</th>
                      <!-- <th class="center column-remove-1">Date Scheduled</th> -->
                      <th class="center">Download Your file!</th>
                      <th class="center">View</th>

                    </tr>
                  </thead>
                  <% @orders_charged.each do |order| %>
                    <tbody>
                      <tr>
                      <td class="center"><%= order.id %></td>
                      <td class="center"><%= order.seller.name %></td>
                      <!-- <td class="center column-remove-1"><%= order.created_at.strftime("%b. %-d, %Y") %></td> -->
                      <td class="center"><%= link_to "Download", order.video_order.video.url %></td>
                      <td class="center"><%= link_to 'View', order_path(order) %></td>
                    </tr>
                    <% end %>
                  </tbody>
                </table>
                <div class="digg_pagination">
                  <%= will_paginate @orders_charged, :param_name => 'orders_charged_page_1', :page_links => false %>
                </div>
            </div>
        </div>
      </div>
    </div>


  <div id="myModal-p" class="modal fade" role="dialog">
    <div class="modal-dialog">

      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Modal Header</h4>
        </div>
        <div class="modal-body">
          <h2>Are you sure?</h2>
          <p>Editing any of your current payment settings will override any
             previous settings and you will need to re-enter your banking data.
            You should only be doing this if you have changed banks or bank accounts,
            have a new location or your banking information has updated on the banks end.</p>
          <%= link_to "Yes", new_stripe_account_path(@user) %>/
          <%= link_to "No", "javascript:void(0)",'data-dismiss': "modal" %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>

    </div>
  </div>