config/routes.rb
Rails.application.routes.draw do

  resources :affiliate_dashboards
  devise_for :affiliates
  resources :affiliates
  resources :video_orders


  authenticated :affiliate do
    get 'a/clients' => 'affiliate_dashboards#clients'

  end

get 'client/:id', to: "affiliate_dashboard#client_page"

  authenticated :user, ->(user) { user.buyer? } do
    get 'c/shouts' => 'customer_dashboard#purchases'
    get 'c/dashboard' => 'customer_dashboard#buyer_dashboard'
  end


  resources :admin_dashboard
  # resources :stripe_accounts
  # resources :user_listings
  mount StripeEvent::Engine, at: '/stripe-events' # provide a custom path


  authenticated :user, ->(user) { user.admin? } do
    mount Blazer::Engine, at: "blazer"

    get 'admin/admins' => 'admin_dashboard#admins'
    get 'admin/users' => 'admin_dashboard#users'
    get 'admin/sellers' => 'admin_dashboard#sellers'
    get 'admin/buyers' => 'admin_dashboard#buyers'
    get 'admin/affiliates' => 'admin_dashboard#affiliates'
    get 'admin/orders' => 'admin_dashboard#orders'
    get 'admin/listings' => 'admin_dashboard#listings'
    get 'admin/analytics' => 'admin_dashboard#website_analytics'


    get 'admin/create_seller' => 'users#new'
    post 'admin/create_seller' => 'users#add_user'

  end

  devise_for :buyers
  resources :orders
  devise_for :users, controllers: { confirmations: 'confirmations' }

  resources :users

  resources :stripe_accounts

  resources :bank_accounts

  resources :orders do
    resources :video_orders
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :listings do
    resources :orders
  end

    resources :orders

resources :bank_accounts


  get 'stripe_show' => "stripe_accounts#show"


  get 'stripe_' => "stripe_account#create"

  get 'stripe_new' => "stripe_account#new"

  get 'cancel' => "orders#cancel_update"


  get 'seller' => "listings#seller"

  get 'edit_stripe' => "stripe_accounts#edit"




  #new_order_sales_upload post '/orders/:order_ids(.:format) sales_uploads#new'
 get 'sales' => "orders#sales"
 post 'sales' => "orders#sales"

  get 'talent' => "listings#listings_page"

  get 'purchases' => "orders#purchases"

  get 'buyer_purchases' => "orders#buyer_purchases"



  get 'dashboard' => "dashboard#dashboard"
  get 'shouts' => "dashboard#tables"
  get 'charts' => "dashboard#charts"
  get 'settings' => "dashboard#settings"
  get 'account' => "dashboard#account"
  get 'payout_destination' => "dashboard#payout_destination"

  get 'account_affiliate' => "affiliate_dashboards#account_affiliate"


get 'auth' => "users#index"

get 'stripe' => "listings#stripe"

get 'analytics' => "dashboard#order_analytics"





  get 'car' => "listings#carousel"

  root to: "listings#index"



end

app/models/listing.rb
class Listing < ApplicationRecord
  mount_uploader :image, ImageUploader
  serialize :image, JSON # If you use SQLite, add this line.


#  validates attachment content type :image, :content type => /\Aimage\/.*\Z/

  validates :name, :description, :price, presence: true
#  validates :price, numericality: { greater than: 0 }
  validates_presence_of :image

  belongs_to :user
  has_and_belongs_to_many :categories  # belongs_to :categories_listings, required: false
  # has_and_belongs_to_many :category, required: false, :through => :categories_listings


  attr_accessor :new_category_name
  before_save :create_category_from_name

  # has_many :categories

  def create_category_from_name
    create_category(name: new_category_name) unless new_category_name.blank?
  end

  has_many :orders
  #has_many :orders through: :sales_uploads



  enum listing_status: { live: 1, hold: 2 }

  def self.search(search)
    where("name LIKE ?","%#{search}%")
  end

#   def self.categories(category_ids)
#   select(:id).distinct.
#     joins(:categories).
#     where('categories.id' => category_ids)
# end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  load_and_authorize_resource
  # layout :admin_layout
  layout :determine_layout, :only => [ :payment, :seller, :edit, :new ]
  # layout "admin", :only => [ :payment, :seller, :edit ]
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  # before_action :check_user, only: [:edit, :update, :destroy]
  # before_action :check_user_seller, only: [:create, :destroy]

  # before_action :user_approved, only: [:create]
  # attr_accessor :new_category_name

  def payment

    # Amount in cents
    @amount = (@listing.price)
    token = params[:stripeToken]
    payment_form = params[:payment_form]

    # customer = Stripe::Customer.create(
    #   :email => params[:stripeEmail],
    #
    # )

    charge = Stripe::Charge.create({
      :source  => params[:stripeToken],
      # :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    })

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path

  end

  def seller
    @listings = Listing.where(user: current_user) #, created_at: :desc)
  end

  def listings_page
    @listings = Listing.all.where(listing_status: [1] )

    if params[:search]
      @listings = Listing.search(params[:search]).order(created_at: :desc)
    else
      @listings = Listing.all.order(created_at: :desc)
    end

    @categories = Category.all
    # if params[:category_id]
    #   @listings = Listing.where(:category_id => params[:category_id])
    # else
    #   @listings = Listing.all
    # end

  end

  def carousel
    @listings = Listing.all
    if params[:search]
      @listings = Listing.search(params[:search]).order(created_at: :desc)
    else
      @listings = Listing.all.order(created_at: :desc)
    end
    @listings_category = Listing.find(params[:category])
  end

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all.where(listing_status: [1] )

    if params[:search]
      @listings = Listing.search(params[:search]).order(created_at: :desc)
    elsif params[:category]
      @listings = Category.find(params[:category]).listings
    else
      @listings = Listing.all.where(listing_status: [1] ).order(created_at: :desc)
    end
    @categories = Category.all


  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    @orders = Order.all.where(seller: current_user).paginate(:page => params[:page], :per_page => 15) || @orders = Order.all.where(seller: current_buyer).paginate(:page => params[:page], :per_page => 15)


    @orders_a = Order.all.where(seller: current_user)
    @orders_month = @orders_a.all.group_by { |mon|  mon.created_at.beginning_of_month }
    @orders_day = @orders_a.all.group_by { |day|  day.created_at.beginning_of_day }
    @orders_date = @orders_a.all.group_by { |day|  day.created_at.beginning_of_day }

    @order = @listing.orders.new()



  end

  # GET /listings/new
  def new
    @listing = Listing.new
    # @categories = Category.all

    # 3.times do
    #   @listing.categories.build
    # end


    # @categories = Category.all.map{|c| [ c.name, c.id ] }
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:attr1, :name, :description, :price, :image, {category_ids: []}, :listing_status)
    end

    def check_user
      if current_user != @listing.user
        redirect_to root_url, alert: "Sorry, this isn't your listing"
      end
    end

    def check_user_seller
      if current_user != (current_user.seller == true )
        redirect_to root_url, alert: "Sorry, this isn't your listing 2"
      end
    end

    def user_approved
      if current_user != (@user.approved == true)
        redirect_to root_url, alert: "Sorry, your account isn't approved, please contact the admins"
      end
    end

    def determine_layout
      current_affiliate ? "affiliate_dashboard" : "admin"
    end

    # def admin_layout
    #   case 'payment'
    #   when 'payment'
    #     'application'
    #   when 'seller'
    #   else
    #     'application'
    #   end
    # end

end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_carousel.html.erb
<% render 'carousel' %>

app/views/listings/index.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  font-family: Arial, Helvetica, sans-serif;
}


</style>
</head>
<div class="container">

  <div class="top">
    <form class="example">
      <!-- <input class="searchTerm"> -->
      <%= form_tag(listings_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], class: "example-form", placeholder: " Search Talent By Name..." %>
      <button type="submit search-submit"><i class="fa fa-search"></i></button>

    </form>
    <% end %>
  </div>

<div class="row row-index">
  <div class="center">
  <h2 class="left-index-display-min">Categories</h2>
  </div>
  <div class="left">
    <h2 class="left-index-display-max">Categories</h2>
        <div class="categories-">

          <% @categories.each do |cat| %>
            <%= link_to cat.name, listings_path(:category => cat), class: "btn ripple-effect btn-cat-2" %>
          <% end %>
          <div class="btn ripple-effect btn-cat-2">Button</div>

    </div>

</div>


  <div class="right">
    <div class="center">
      <h1>Talent</h1>
    </div>

<div class="product-">
  <!-- <div class="row"> -->
      <% @listings.each do |listing| %>
      <div class="image-circle">
        <div class="listing-page-images" id="listing-image-resize">
            <%= link_to image_tag(listing.image_url(:listing_index_4), id: "listing-image-resize-2"), listing, data: {id: listing.id, name: listing.name} %>
        </div>
          <div class="text-over">
            <p><%= link_to listing.user.name, listing, id: "" %></p>
          </div>
      </div>

        <% end %>
    <!-- </div> -->

  <!-- <div class="row">
      <% @listings.each do |listing| %>
      <div class="image-circle">
        <div class="card listing-page-images-2">
          <%= link_to image_tag(listing.image_url(:thumb)), listing %>
            <div class="card-img-overlay text-over">
              <p><%= link_to listing.user.name, listing %></p>
            </div>
          </div>
        </div>

        <% end %>
      </div>
    </div>  -->
</div>



  <script>

  function myFunction() {
      var input, filter, ul, li, a, i;
      input = document.getElementById("mySearch");
      filter = input.value.toUpperCase();
      ul = document.getElementById("myMenu");
      li = ul.getElementsByTagName("li");
      for (i = 0; i < li.length; i++) {
          a = li[i].getElementsByTagName("a")[0];
          if (a.innerHTML.toUpperCase().indexOf(filter) > -1) {
              li[i].style.display = "";
          } else {
              li[i].style.display = "none";
          }
      }
  }



$(document).ready(function(){
    $('.example-form')
        .focusout(function(){
            $( this ).removeClass('inputactive');
        })
        .click(function(){
            $( this ).addClass('inputactive');
        })
        // .mouseenter(function() {
        //     $( this ).addClass('mouseover');
        // })
        // .mouseleave(function() {
        //     $( this ).removeClass('mouseover');
        // });
});


(function($) {
    $(".ripple-effect").click(function(e){
        var rippler = $(this);

        if(rippler.find(".ink").length == 0) {
            rippler.append("<span class='ink'></span>");
        }

        var ink = rippler.find(".ink");

        ink.removeClass("animate");

        if(!ink.height() && !ink.width())
        {
            var d = Math.max(rippler.outerWidth(), rippler.outerHeight());
            ink.css({height: d, width: d});
        }

        var x = e.pageX - rippler.offset().left - ink.width()/2;
        var y = e.pageY - rippler.offset().top - ink.height()/2;

        ink.css({
          top: y+'px',
          left:x+'px'
        }).addClass("animate");
    })
})(jQuery);

  </script>



</div>
</html>

app/views/listings/listings_page.html.erb
<!-- <div class="listing"> -->

<!-- Load icon library -->
<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> -->



<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  font-family: Arial, Helvetica, sans-serif;
}


</style>
</head>
<body class="body-listing">

<div class="row">
  <div class="top">
    <form class="example">
      <%= form_tag(listings_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Talent" %>
      <button type="submit"><i class="fa fa-search"></i></button>

    </form>
    <% end %>
  </div>
</div>









<div class="row">
  <div class="left">
    <h2>Categories</h2>
      <form class="example">
        <%= form_tag(listings_path, :method => "get", id: "search-form") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search Talent" %>
      </form>
    <% end %>
      <% @categories.each do |cat| %>
        <%= link_to cat.name, listings_path(:category => cat), class: "btn btn-primary-2" %>
      <% end %>
  </div>

  <div class="right">
    <div class="center">
    <h1>Talent</h1>
  </div>

<div id="container">
  <div class="row">
    <% @listings.each do |listing| %>
      <div class="card deck" style="width:250px">

              <img class="card-img-top" src="" alt="">

                <%= link_to image_tag(listing.image_url(:thumb)), listing %>
                <div class="card-text"><%= listing.user.name %></div>
                <!-- <div class="text-over">
                  <div class="caption">
                    <p><%= listing.user.name %></p>
                  </div>

              </div> -->
            </div>
    <% end %>
          </div>
        </div>
      </div>
    </div>



  <script>
  function myFunction() {
      var input, filter, ul, li, a, i;
      input = document.getElementById("mySearch");
      filter = input.value.toUpperCase();
      ul = document.getElementById("myMenu");
      li = ul.getElementsByTagName("li");
      for (i = 0; i < li.length; i++) {
          a = li[i].getElementsByTagName("a")[0];
          if (a.innerHTML.toUpperCase().indexOf(filter) > -1) {
              li[i].style.display = "";
          } else {
              li[i].style.display = "none";
          }
      }
  }
  </script>


</body>
</html>

app/views/listings/seller.html.erb
<!--

<!doctype html>
<html lang="en">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

<% if (user_signed_in?) %>
  <%= link_to 'New Listing', new_listing_path %>
<% end %>

<div class="center">
  <h1>Your Seller Page</h1>
</div>
</head>

<body>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  <table class="table table-dark">
    <thead>
      <tr>
        <th class="center">Talent Name</th>
        <th class="center">Description</th>
        <th class="center">Price</th>
        <th class="center">Action</th>
      </tr>
    </thead>
    <% @listings.each do |listing| %>
      <tbody>
        <tr>
        <td class="center"><%= listing.name %></td>
        <td class="center"><%= listing.description %></td>
        <td class="center"><%= number_to_currency(listing.price) %></td>
        <td class="center">
          <div class="btn-group">
            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
              Action
            </button>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'View', listing, class: "btn btn-link" %></li>
              <li><%= link_to 'Edit', edit_listing_path(listing), class: "btn btn-link" %></li>
              <li><%= link_to 'Destroy', listing, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-link" %></li>
            </ul>
          </div>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</body>

-->

                    <div class="card-deck">
                        <div class="col-md-12">
                            <div class="card scroll">
                                <div class="card-header ">
                                    <h4 class="card-title">Your Listing(s)</h4>
                                    <p class="card-category">Edit or update your listing(s) information here</p>
                                </div>
                                <div class="card-body ">
                                  <div data-spy="scroll" data-offset="0">
                                    <% if (user_signed_in?) %>
                                      <%= link_to 'New Listing', new_listing_path, class: "btn btn-light btn-margin-bottom" %>
                                    <% end %>


                                    <!-- </head>

                                    <body> -->



                                      <table class="table table-hover">
                                        <thead>
                                          <tr>
                                            <th class="center">Talent Name</th>
                                            <th class="center column-remove-1">Description</th>
                                            <th class="center column-remove-1">Price</th>
                                            <th class="center">Status</th>
                                            <th class="center">Action</th>
                                          </tr>
                                        </thead>
                                        <% @listings.each do |listing| %>
                                          <tbody>
                                            <tr>
                                            <td class="center"><%= listing.name %></td>
                                            <td class="center column-remove-1"><%= listing.description %></td>
                                            <td class="center column-remove-1"><%= number_to_currency(listing.price) %></td>
                                            <td class="center"><%= listing.listing_status %></td>
                                            <td class="center">
                                                <%= link_to edit_listing_path(listing), class: "btn btn-link" do %>
                                                  <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                                <% end %>
                                            </td>
                                          </tr>
                                          <% end %>
                                        </tbody>
                                      </table>
                                    <!-- </body>
                                    </html> -->
                            </div>
                        </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
          </div>

        </div>
    </div>

</body>



</html>

app/views/listings/show.html.erb
<% ahoy.track "Listing Viewed", listing_id: @listing.id %>

<head>



</head>


<div class="jumbotron jumbotron-2">
  <div class="row">
    <div class="image-circle-show">
      <div class="listing-show-images">
        <%= image_tag @listing.image_url(:thumb) %>
      </div>
    </div>
  </div>
  <br>
  <div class="center">
    <div class="row bs-wizard" style="border-bottom:0;">
        <div class="col-4 bs-wizard-step complete">
            <div class="text-center bs-wizard-stepnum">Step 1<i class="fa fa-mobile fa-1x" aria-hidden="true"></i>
            </div>
            <div class="progress">
                <div class="progress-bar"></div>
            </div> <a class="bs-wizard-dot" data-toggle="tooltip" data-placement="left" title="Your purchase is put on hold and you&apos;re not charged until the ORDER is complete."></a>
            <div
            class="bs-wizard-info text-center">Request!</div> <a class="bs-wizard-dot-2" data-toggle="tooltip" data-placement="top"
            title="During this time you can edit or cancel your Order."></a>
            </div>
        <div class="col-4 bs-wizard-step complete">
          <div class="text-center bs-wizard-stepnum">Step 2</div>
          <div class="progress">
              <div class="progress-bar"></div>
          </div> <a class="bs-wizard-dot" data-toggle="tooltip" data-placement="top" title="Once uploaded, you can then Get Your Order!"></a>
          <div class="bs-wizard-info text-center">Talent uploads!</div>
          </div>
        <div class="col-4 bs-wizard-step complete">
          <div class="text-center bs-wizard-stepnum">Step 3</div>
          <div class="progress">
              <div class="progress-bar"></div>
          </div> <a class="bs-wizard-dot" data-toggle="tooltip" data-placement="right"
          title="Get Your yoyo from either your dashboard, by email, or by text."></a>
          <div
          class="bs-wizard-info text-center">GET YOUR SHOUT!</div>
          </div>
        </div>
      </div>
    </div>
  </div>

<div class="body-listing">


    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">




      <div class="card-deck">
        <div class="margin-auto">
        <div class="col-md-12">
              <div class="card">
                <div class="card-header">
                  <div class="center-4">
                          <h2>
                            <%= @listing.name %>
                          </h2>
                          <h5>
                            <%= @listing.description %>
                          </h5>
                          <p>
                            <% if @listing.orders.where(order_status: [2] ).present? %>
                            Usually responds in
                            <%= (@listing.orders.where(order_status: [2] ).sum { |orders| orders.updated_at.day - orders.created_at.day } / @listing.orders.where(order_status: [2] ).count )  %>
                              Days
                              <% end %>

                          </p>
                      </div>
                <hr>
                  <div class="center-4">
                  <h2>Create your Shout!</h2>
                </div>
                </div>
                <div class="card-body">

                  <%= form_for(@order, url: listing_orders_path(@listing)) do |form| %>

                    <% if @order.errors.any? %>
                      <div id="error_explanation">
                        <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

                        <ul>
                        <% order.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                        <% end %>
                        </ul>
                      </div>
                    <% end %>

                    <div class="form-group">
                      <%= form.label :name, "Who's the Shout for?" %>
                      <%= form.text_field :name, class: "form-control", required: true %>
                    </div>

                    <div class="form-group">
                      <%= form.label :email, "Your Email Address -- (You can send the Shout to a new email once uploaded!)" %>
                      <%= form.text_field :email, class: "form-control", required: true   %>
                    </div>

                    <div class="form-group">
                      <%= form.label :description, "Describe to Talent what to say -- (Be as detailed as you can!)" %>
                      <%= form.text_area :description, class: "form-control", :rows => 10, required: true    %>
                    </div>

                    <script

                      src="https://js.stripe.com/v3/">

                    </script>

                    <% if @listing.listing_status["hold"] %>
                      <a href="/" class="btn btn-info ripple-effect" role="button" id="button-element-2">This Shout is on hold, view all Talent</a>
                    <% else %>

                      <div class="form-row">
                        <label for="card-element">
                          Credit or debit card
                        </label>
                        <div id="card-element" class="form-control">
                        </div>

                        <div id="card-errors" role="alert"></div>
                      </div>
                        <br>
                        <div class="form-group">

                          <!-- <%= form.hidden_field :stripe_customer_token %> -->

                      <%= form.submit "Create Shout for #{number_to_currency(@listing.price)}", class:"ripple-effect", id:"button-element" %>

                    </div>

                    <span class="token"></span>
                    <!-- </form> -->
                    <% end %>
                    <% end %>

                    </div>


                </div>
            </div>
          </div>
        </div>


      <script>

      $(function () {
        $('[data-toggle="tooltip"]').tooltip()
      })

      $(document).ready(function(){
          $("#myBtnOrderClick").click(function(){
              $("#OrderModal").modal();
          });
      });






      (function($) {
          $(".ripple-effect").click(function(e){
              var rippler = $(this);

              // create .ink element if it doesn't exist
              if(rippler.find(".ink").length == 0) {
                  rippler.append("<span class='ink'></span>");
              }

              var ink = rippler.find(".ink");

              // prevent quick double clicks
              ink.removeClass("animate");

              // set .ink diametr
              if(!ink.height() && !ink.width())
              {
                  var d = Math.max(rippler.outerWidth(), rippler.outerHeight());
                  ink.css({height: d, width: d});
              }

              // get click coordinates
              var x = e.pageX - rippler.offset().left - ink.width()/2;
              var y = e.pageY - rippler.offset().top - ink.height()/2;

              // set .ink position and add class .animate
              ink.css({
                top: y+'px',
                left:x+'px'
              }).addClass("animate");
          })
      })(jQuery);

      </script>

    </div>



  <script>





  // Create a Stripe client.
  var stripe = Stripe('pk_test_WUSowiZS0TqTSqQJucPWU8kh');

  // Create an instance of Elements
  var elements = stripe.elements();

  // Custom styling can be passed to options when creating an Element.
  // (Note that this demo uses a wider set of styles than the guide below.)
  var style = {
    base: {
      color: '#32325d',
      lineHeight: '24px',
      fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
      fontSmoothing: 'antialiased',
      fontSize: '16px',
      '::placeholder': {
        color: '#aab7c4'
      }
    },
    invalid: {
      color: '#fa755a',
      iconColor: '#fa755a'
    }
  };

  // Create an instance of the card Element
  var card = elements.create('card', {style: style});

  // Add an instance of the card Element into the `card-element` <div>
  card.mount('#card-element');

  // Handle real-time validation errors from the card Element.
  card.addEventListener('change', function(event) {
    var displayError = document.getElementById('card-errors');
    if (event.error) {
      displayError.textContent = event.error.message;
    } else {
      displayError.textContent = '';
    }
  });

  // Handle form submission
  var form = document.getElementById('payment_form');
  form.addEventListener('submit', function(event) {
    event.preventDefault();

    stripe.createToken(card).then(function(result) {
      if (result.error) {
        // Inform the user if there was an error
        var errorElement = document.getElementById('card-errors');
        errorElement.textContent = result.error.message;
      } else {
        // Send the token to your server
        stripeTokenHandler(result.token);
      }
    });
  });

    function stripeTokenHandler(token) {
      // Insert the token ID into the form so it gets submitted to the server
      var form = document.getElementById('payment_form');
      var hiddenInput = document.createElement('input');
      hiddenInput.setAttribute('type', 'hidden');
      hiddenInput.setAttribute('name', 'stripeToken');
      hiddenInput.setAttribute('value', token.id);
      form.appendChild(hiddenInput);

      // Submit the form
      form.submit();
    }



</script>

<!-- <%= link_to "Get your order for", new_listing_order_path(@listing), class: 'btn btn-primary' %> -->