config/routes.rb
Rails.application.routes.draw do

  resources :affiliate_dashboards
  devise_for :affiliates
  resources :affiliates
  resources :video_orders


  authenticated :affiliate do
    get 'a/clients' => 'affiliate_dashboards#clients'

  end

get 'client/:id', to: "affiliate_dashboard#client_page"

  authenticated :user, ->(user) { user.buyer? } do
    get 'c/shouts' => 'customer_dashboard#purchases'
    get 'c/dashboard' => 'customer_dashboard#buyer_dashboard'
  end


  resources :admin_dashboard
  # resources :stripe_accounts
  # resources :user_listings
  mount StripeEvent::Engine, at: '/stripe-events' # provide a custom path


  authenticated :user, ->(user) { user.admin? } do
    mount Blazer::Engine, at: "blazer"

    get 'admin/admins' => 'admin_dashboard#admins'
    get 'admin/users' => 'admin_dashboard#users'
    get 'admin/sellers' => 'admin_dashboard#sellers'
    get 'admin/buyers' => 'admin_dashboard#buyers'
    get 'admin/affiliates' => 'admin_dashboard#affiliates'
    get 'admin/orders' => 'admin_dashboard#orders'
    get 'admin/listings' => 'admin_dashboard#listings'
    get 'admin/analytics' => 'admin_dashboard#website_analytics'


    get 'admin/create_seller' => 'users#new'
    post 'admin/create_seller' => 'users#add_user'

  end

  devise_for :buyers
  resources :orders
  devise_for :users, controllers: { confirmations: 'confirmations' }

  resources :users

  resources :stripe_accounts

  resources :bank_accounts

  resources :orders do
    resources :video_orders
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :listings do
    resources :orders
  end

    resources :orders

resources :bank_accounts


  get 'stripe_show' => "stripe_accounts#show"


  get 'stripe_' => "stripe_account#create"

  get 'stripe_new' => "stripe_account#new"

  get 'cancel' => "orders#cancel_update"


  get 'seller' => "listings#seller"

  get 'edit_stripe' => "stripe_accounts#edit"




  #new_order_sales_upload post '/orders/:order_ids(.:format) sales_uploads#new'
 get 'sales' => "orders#sales"
 post 'sales' => "orders#sales"

  get 'talent' => "listings#listings_page"

  get 'purchases' => "orders#purchases"

  get 'buyer_purchases' => "orders#buyer_purchases"



  get 'dashboard' => "dashboard#dashboard"
  get 'shouts' => "dashboard#tables"
  get 'charts' => "dashboard#charts"
  get 'settings' => "dashboard#settings"
  get 'account' => "dashboard#account"
  get 'payout_destination' => "dashboard#payout_destination"

  get 'account_affiliate' => "affiliate_dashboards#account_affiliate"


get 'auth' => "users#index"

get 'stripe' => "listings#stripe"

get 'analytics' => "dashboard#order_analytics"





  get 'car' => "listings#carousel"

  root to: "listings#index"



end

app/models/user_listing.rb
class UserListing < ApplicationRecord

  belongs_to :user
  belongs_to :listing

  validates :link, uniqueness: true
  
end

app/controllers/user_listings_controller.rb
class UserListingsController < ApplicationController
  before_action :set_user_listing, only: [:show, :edit, :update, :destroy]

  # GET /user_listings
  # GET /user_listings.json
  def index
    @user_listings = UserListing.all
  end

  # GET /user_listings/1
  # GET /user_listings/1.json
  def show
    listing = UserListingLink.find_by(link: params[:user_link]).listing
    redirect_to listings_path(listing)
  end

  # GET /user_listings/new
  def new
    @user_listing = UserListing.new
  end

  # GET /user_listings/1/edit
  def edit
  end

  # POST /user_listings
  # POST /user_listings.json
  def create
    @user_listing = UserListing.new(user_listing_params)

    respond_to do |format|
      if @user_listing.save
        format.html { redirect_to @user_listing, notice: 'User listing was successfully created.' }
        format.json { render :show, status: :created, location: @user_listing }
      else
        format.html { render :new }
        format.json { render json: @user_listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_listings/1
  # PATCH/PUT /user_listings/1.json
  def update
    respond_to do |format|
      if @user_listing.update(user_listing_params)
        format.html { redirect_to @user_listing, notice: 'User listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_listing }
      else
        format.html { render :edit }
        format.json { render json: @user_listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_listings/1
  # DELETE /user_listings/1.json
  def destroy
    @user_listing.destroy
    respond_to do |format|
      format.html { redirect_to user_listings_url, notice: 'User listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_listing
      @user_listing = UserListing.find(params[:id, :user_link])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_listing_params
      params.fetch(:user_listing, {})
    end
end

app/helpers/user_listings_helper.rb
module UserListingsHelper
end

app/views/user_listings/_form.html.erb
<%= form_with(model: user_listing, local: true) do |form| %>
  <% if user_listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_listing.errors.count, "error") %> prohibited this user_listing from being saved:</h2>

      <ul>
      <% user_listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_listings/edit.html.erb
<h1>Editing User Listing</h1>

<%= render 'form', user_listing: @user_listing %>

<%= link_to 'Show', @user_listing %> |
<%= link_to 'Back', user_listings_path %>

app/views/user_listings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Listings</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_listings.each do |user_listing| %>
      <tr>
        <td><%= link_to 'Show', user_listing %></td>
        <td><%= link_to 'Edit', edit_user_listing_path(user_listing) %></td>
        <td><%= link_to 'Destroy', user_listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Listing', new_user_listing_path %>

app/views/user_listings/new.html.erb
<h1>New User Listing</h1>

<%= render 'form', user_listing: @user_listing %>

<%= link_to 'Back', user_listings_path %>

app/views/user_listings/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_listing_path(@user_listing) %> |
<%= link_to 'Back', user_listings_path %>